# Copyright (c) 2015 Hewlett-Packard Development Company, L.P.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Inspector - (re)starting ironic-inspector service"
  service:
    name: ironic-inspector
    state: restarted
    enabled: yes
  when: enable_inspector | bool

- name: "Stop inspector if it is disabled"
  service:
    name: ironic-inspector
    state: stopped
    enabled: no
  ignore_errors: true
  when: not enable_inspector | bool

- name: "Remove inspector if it is disabled"
  file:
    path: "{{ init_dest_dir }}ironic-inspector.service"
    state: absent
  when: not enable_inspector | bool
