# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: "Set up IPE data dir"
  file:
    name: "{{ prometheus_exporter_data_dir }}"
    owner: ironic
    group: ironic
    state: directory
    mode: "0750"

- name: "Ensure IPE Flask Application is configured on systemd"
  template:
    src: ironic-prometheus-exporter.service.j2
    dest: /etc/systemd/system/ironic-prometheus-exporter.service
    owner: root
    group: root
    mode: "0644"
  become: true
  register: ironic_prometheus_exporter_service_file

- name: "Ensure IPE Flask Application systemd service is started and enabled"
  systemd:
    name: ironic-prometheus-exporter
    enabled: yes
    state: started
    daemon_reload: "{{ ironic_prometheus_exporter_service_file.changed }}"
  become: true
