[tox]
minversion = 4.28.0
envlist = py3,pep8

[testenv]
usedevelop = True
setenv =
    VIRTUAL_ENV={envdir}
    PYTHONDONTWRITEBYTECODE=1
    PYTHONUNBUFFERED=1
    PYTHONWARNINGS=default::DeprecationWarning
constraints=
  {env:TOX_CONSTRAINTS_FILE:https://releases.openstack.org/constraints/upper/master}
deps =
  -r{toxinidir}/requirements.txt
  -r{toxinidir}/test-requirements.txt
commands =
    stestr run --slowest {posargs}
passenv = http_proxy
          HTTP_PROXY
          https_proxy
          HTTPS_PROXY
          no_proxy
          NO_PROXY

[testenv:pep8]
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure {posargs}

[testenv:bandit]
deps = {[testenv:pep8]deps}
commands = pre-commit run --all-files --show-diff-on-failure bandit

[testenv:codespell]
description =
  Run codespell to check spelling
deps = {[testenv:pep8]deps}
commands = pre-commit run --all-files --show-diff-on-failure codespell

[testenv:cover]
setenv = {[testenv]setenv}
         PYTHON=coverage run --source bifrost --parallel-mode
commands =
  coverage erase
  stestr run {posargs}
  coverage combine
  coverage report
  coverage html -d ./cover

[testenv:docs]
deps =
  -r{toxinidir}/doc/requirements.txt
commands = sphinx-build -W -j auto -E -b html doc/source doc/build/html

[testenv:pdf-docs]
allowlist_externals = make
deps = {[testenv:docs]deps}
commands =
  sphinx-build -W -b latex doc/source doc/build/pdf
  make -C doc/build/pdf

[testenv:debug]
commands = oslo_debug_helper -t bifrost/tests {posargs}

[testenv:releasenotes]
usedevelop = False
deps =
  -r{toxinidir}/doc/requirements.txt
commands =
  sphinx-build -a -E -W -d releasenotes/build/doctrees -b html releasenotes/source releasenotes/build/html

[testenv:venv]
setenv = PYTHONHASHSEED=0
allowlist_externals = *
deps =
  -r{toxinidir}/test-requirements.txt
  -r{toxinidir}/doc/requirements.txt
commands = {posargs}

[testenv:linters]
allowlist_externals = bash
deps =
  ansible>=10,<11
  ansible-lint>=25,<26
commands =
  bash tools/ansible-lint.sh

[flake8]
# [W503] Line break before binary operator.
# Ignore all E and F rules - handled by ruff instead
ignore = E,F,W503
# re-enable some pycodestyle checks due to
# https://github.com/astral-sh/ruff/issues/2402
extend-select = E122,E124,E125,E127,E128,E131,E704
filename = *.py
exclude = .*,dist,doc,*lib/python*,*egg,build,playbooks/library
import-order-style = pep8
application-import-names = bifrost
# [H106] Don't put vim configuration in source files.
enable-extensions = H106
