---
# Test role defaults
networking_json_rpc_port: 8090
networking_switch_config_file: "/etc/ironic/networking/switch-configs.conf"
ans_network_interface: "{{ network_interface | replace('-', '_') }}"
internal_ip: "{{ hostvars[inventory_hostname]['ansible_' + ans_network_interface]['ipv4']['address'] }}"
