- project:
    templates:
      - openstack-python3-yoga-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - bifrost-tox-linters
        - bifrost-integration-tinyipa-centos-9
        - bifrost-integration-tinyipa-ubuntu-focal
        - bifrost-integration-tinyipa-keystone-ubuntu-focal
        - bifrost-integration-tinyipa-keystone-centos-9
        - bifrost-integration-tinyipa-debian-bullseye
        - bifrost-integration-redfish-vmedia-uefi-ubuntu-focal
        - bifrost-integration-redfish-vmedia-uefi-centos-9
        - bifrost-upgrade-ubuntu-focal
        # Non-voting jobs
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - bifrost-integration-dhcp-ubuntu-focal:
            voting: false
        - bifrost-integration-dhcp-centos-9:
            voting: false
        - bifrost-integration-dibipa-debian-ubuntu-focal:
            voting: false
        - bifrost-integration-dibipa-debian-centos-9:
            voting: false
        - bifrost-cli-ubuntu-focal:
            voting: false
        - bifrost-collections-src:
            voting: false
        - bifrost-keystone-collections-src:
            voting: false
    gate:
      jobs:
        - bifrost-tox-linters
        - bifrost-integration-tinyipa-centos-9
        - bifrost-integration-tinyipa-ubuntu-focal
        - bifrost-integration-tinyipa-keystone-ubuntu-focal
        - bifrost-integration-tinyipa-keystone-centos-9
        - bifrost-integration-tinyipa-debian-bullseye
        - bifrost-integration-redfish-vmedia-uefi-ubuntu-focal
        - bifrost-integration-redfish-vmedia-uefi-centos-9
        - bifrost-upgrade-ubuntu-focal
    experimental:
      jobs:
        - bifrost-benchmark-ironic
