- project:
    templates:
      - openstack-python3-xena-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - bifrost-tox-linters
        - bifrost-integration-tinyipa-ubuntu-focal
        - bifrost-integration-tinyipa-keystone-ubuntu-focal
        - bifrost-integration-redfish-vmedia-uefi-ubuntu-focal
        # Non-voting jobs
        - bifrost-integration-tinyipa-ubuntu-bionic:
            voting: false
        - bifrost-integration-dhcp-ubuntu-focal:
            voting: false
        - bifrost-integration-dibipa-debian-ubuntu-focal:
            voting: false
        - bifrost-cli-ubuntu-focal:
            voting: false
        - bifrost-collections-src:
            voting: false
        - bifrost-keystone-collections-src:
            voting: false
    gate:
      jobs:
        - bifrost-tox-linters
        - bifrost-integration-tinyipa-ubuntu-focal
        - bifrost-integration-tinyipa-keystone-ubuntu-focal
    experimental:
      jobs:
        - bifrost-benchmark-ironic
