- project:
    templates:
      - openstack-python3-jobs
      - check-requirements
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - bifrost-tox-linters
        - bifrost-integration-tinyipa-centos-9
        - bifrost-integration-tinyipa-ubuntu-jammy
        - bifrost-integration-tinyipa-keystone-ubuntu-jammy
        - bifrost-integration-tinyipa-keystone-centos-9
        - bifrost-integration-tinyipa-debian-bullseye
        - bifrost-integration-redfish-vmedia-uefi-ubuntu-jammy
        - bifrost-integration-redfish-vmedia-uefi-centos-9
        - bifrost-upgrade-ubuntu-focal
        - bifrost-upgrade-keystone-centos9
        # Non-voting jobs
        - bifrost-integration-tinyipa-keystone-ubuntu-focal:
            voting: false
        - bifrost-integration-tinyipa-fedora-latest:
            voting: false
        - bifrost-integration-redfish-uefi-fedora-latest:
            voting: false
        - bifrost-integration-dhcp-ubuntu-jammy:
            voting: false
        - bifrost-integration-dhcp-centos-9:
            voting: false
        - bifrost-integration-dibipa-debian-ubuntu-jammy:
            voting: false
        - bifrost-integration-dibipa-debian-centos-9:
            voting: false
        - bifrost-cli-ubuntu-jammy:
            voting: false
        - bifrost-collections-src:
            voting: false
            # FIXME(dtantsur): downgrade ansible-collections-openstack
            # and openstacksdk because the former has not been ported
            # yet to openstacksdk >=0.99.0
            required-projects: &bifrost_collections_required_projects
              - name: openstack/ansible-collections-openstack
                override-checkout: stable/1.0.0
              - name: openstack/openstacksdk
                override-checkout: stable/yoga
        - bifrost-keystone-collections-src:
            voting: false
            # FIXME(dtantsur): downgrade ansible-collections-openstack
            # and openstacksdk because the former has not been ported
            # yet to openstacksdk >=0.99.0
            required-projects: *bifrost_collections_required_projects
        - kolla-ansible-ubuntu-bifrost:
            voting: false
            # NOTE(yoctozepto): to override from job definition
            files: .*
            irrelevant-files:
              - ^.*\.rst$
              - ^bifrost/tests/.*$
              - ^api-ref/.*$
              - ^doc/.*$
              - ^releasenotes/.*$
              - ^setup.cfg$
              - ^test-requirements.txt$
              - ^tools/.*$
              - ^tox.ini$
    gate:
      jobs:
        - bifrost-tox-linters
        - bifrost-integration-tinyipa-centos-9
        - bifrost-integration-tinyipa-ubuntu-jammy
        - bifrost-integration-tinyipa-keystone-ubuntu-jammy
        - bifrost-integration-tinyipa-keystone-centos-9
        - bifrost-integration-tinyipa-debian-bullseye
        - bifrost-integration-redfish-vmedia-uefi-ubuntu-jammy
        - bifrost-integration-redfish-vmedia-uefi-centos-9
        - bifrost-upgrade-ubuntu-focal
        - bifrost-upgrade-keystone-centos9
    experimental:
      jobs:
        - bifrost-benchmark-ironic
