# Create a default VM
---
- name: "Executes install, enrollment, and testing in one playbook"
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: "Set default baremetal.json file if not already defined"
      set_fact:
         baremetal_json_file: "/tmp/baremetal.json"
      when: baremetal_json_file is not defined
    - name: "Set variables if running in the CI"
      set_fact:
         copy_from_local_path: true
         git_url_root: "{{ lookup('env', 'WORKSPACE') }}"
      when: lookup('env', 'ZUUL_BRANCH') | length > 0
  roles:
    - role: bifrost-create-vm-nodes
